### Get index
GET /
@host: 127.0.0.1
@port: 3000


### Signup
POST /api/v1/auth/signup
@host: 127.0.0.1
@port: 3000
Content-type: application/json

{
	"userType": "1",
	"firstName": "joe",
	"lastName": "doe",
	"email": "joedoe@test.test",
	"password": "joedoe123456",
	"confirmPassword": "joedoe123456"
}